server:
  port: 9002
spring:
  application:
    name: user-service
    
  #H2 Datasource
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:db
    username: me
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect