FROM openjdk:22-jdk-slim-buster AS build
WORKDIR /app

#Build jar
COPY . .
RUN chmod +x mvnw
RUN ./mvnw clean package -DskipTests

#Run the application
COPY /app/target/*.jar program.jar
ENTRYPOINT ["java", "-jar", "program.jar"]